# Generated by Django 3.0.7 on 2020-10-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('priority', models.IntegerField(choices=[(0, 'I can hold it in'), (1, 'I kinda have to go now'), (2, 'I GOTTA SHIT')], default=0, null=True)),
            ],
        ),
    ]
