# Generated by Django 3.0.7 on 2020-10-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='NeedPost',
        ),
    ]
