# Generated by Django 3.0.7 on 2020-10-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_havetoilet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='havetoilet',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/profile_pics'),
        ),
    ]
